os: linux

addons:
  apt:
    packages:
      libdbus-glib-1-dev

language: python
python: "3.6"

branches:
    only: master

env:
    matrix:
        - TASK=fmt-travis
        - TASK=lint
        - TASK=test
        - TASK=coverage

script: make -f Makefile $TASK
